import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import Particles from "react-tsparticles";

const Home: NextPage = () => {




  
  return (
    <div>
      <Head>
        <title> Akara market</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main >
       
        <Hero />
     
      </main>
     
    </div>
  );
};

export default Home;
