import type { NextPage } from 'next';
import Head from 'next/head';




const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Akara market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative container flex flex-col bg-black h-screen">
        
        <div className="bg-black text-white h-full flex flex-col">
         
        </div>
      </main>
    </div>
  );
};

export default Home;
